play.http.secret.key = "changeme-development-only-do-not-use-in-production-aaaaaaaaaaaaaaaa"
play.http.secret.key = ${?APPLICATION_SECRET}

play.i18n.langs = ["en"]

play.filters.hosts {
  allowed = ["localhost:9000", "localhost", "."]
}
